spring:
  r2dbc:
    url: ${SPRING_R2DBC_URL:r2dbc:postgresql://localhost:5432/user_service}
    username: ${SPRING_R2DBC_USERNAME:csadmin}
    password: ${SPRING_R2DBC_PASSWORD:csadmin123}
  flyway:
    enabled: true
    url: ${SPRING_FLYWAY_URL:jdbc:postgresql://localhost:5432/user_service}
    user: ${SPRING_FLYWAY_USER:csadmin}
    password: ${SPRING_FLYWAY_PASSWORD:csadmin123}
    baseline-on-migrate: true
  application:
    name: user-service
  profiles:
    active: dev

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8082

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    disable-swagger-default-url: true

jwt:
  secret: njkznjknccxw
  expiration: 3600000